# Generated by Django 4.2.18 on 2025-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_reservationcontents_likes_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
