# Generated by Django 4.2.18 on 2025-03-28 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_postlike_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimages',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, verbose_name='reservation_images/'),
        ),
    ]
