# Generated by Django 4.2.18 on 2025-03-28 13:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_reservationimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationimages',
            name='image_url',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='reservation_images/'),
        ),
    ]
