# Generated by Django 4.2.18 on 2025-04-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0005_alter_reservationimages_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservationdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservationdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reservationdetails',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.reservationcontents')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.reservationdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
