# Generated by Django 4.2.18 on 2025-04-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_reservationdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
