# Generated by Django 4.2.18 on 2025-04-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_reservationdetails_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='post',
            new_name='housing',
        ),
    ]
