# Generated by Django 4.2.18 on 2025-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_reservationdetails_booking_reservationdetails_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='housing',
            new_name='house',
        ),
    ]
