# Generated by Django 4.2.18 on 2025-04-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_rename_housing_reservationdetails_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetails',
            name='status',
        ),
    ]
