# Generated by Django 4.2.18 on 2025-04-07 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_remove_reservationdetails_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdetails',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='reservationdetails',
            index=models.Index(fields=['-created'], name='contents_re_created_3ecd30_idx'),
        ),
    ]
