# Generated by Django 4.2.18 on 2025-04-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_reservationdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='contents.reservationcontents'),
        ),
    ]
