# Generated by Django 4.2.20 on 2025-04-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_alter_reservationdetails_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdetails',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reservationdetails',
            name='contents_re_created_3ecd30_idx',
        ),
    ]
