# Generated by Django 4.2.20 on 2025-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_alter_reservationdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
