# Generated by Django 4.2.20 on 2025-04-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_alter_reservationdetails_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='first_name',
            new_name='guest_first_name',
        ),
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='last_name',
            new_name='guest_last_name',
        ),
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='phone_number',
            new_name='guest_phone_number',
        ),
    ]
