# Generated by Django 4.2.18 on 2025-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_email_remove_payment_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
