# Generated by Django 4.2.18 on 2025-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=13),
        ),
    ]
