# Generated by Django 4.2.18 on 2025-04-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_alter_reservationdetails_house'),
        ('payments', '0006_alter_payment_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='house',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='housenames', to='contents.reservationcontents'),
            preserve_default=False,
        ),
    ]
