# Generated by Django 4.2.18 on 2025-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
