# Generated by Django 4.2.18 on 2025-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='user_images/Good_things_are_coming_fOD6Mp2.png', upload_to='user_images/'),
        ),
    ]
