# Generated by Django 4.2.20 on 2025-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
