# Generated by Django 4.2.20 on 2025-04-15 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_verificationtoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='otp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000, message='OTP must be 6 digits.'), django.core.validators.MaxValueValidator(999999, message='OTP must be 6 digits.')]),
        ),
    ]
