# Generated by Django 4.2.20 on 2025-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_verificationtoken_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Token', 'verbose_name_plural': 'Verification Tokens'},
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_ve_user_id_970d34_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['otp'], name='accounts_ve_otp_ee0b9a_idx'),
        ),
    ]
