# Generated by Django 4.2.20 on 2025-04-15 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_verificationtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='otp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='OTP must be 6 digits.'), django.core.validators.MaxValueValidator(9999, message='OTP must be 6 digits.')]),
        ),
    ]
