# Generated by Django 4.2.20 on 2025-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_verificationtoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='media/user_images/Good_things_are_coming_fOD6Mp2.png', upload_to='user_images/'),
        ),
    ]
