# Generated by Django 4.2.20 on 2025-04-17 08:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_verificationtoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_images/default.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='user_images/'),
        ),
    ]
