# Generated by Django 4.2.20 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='{Front_end}/media/user_images/Good_things_are_coming_fOD6Mp2.png', upload_to='user_images/'),
        ),
    ]
