# Generated by Django 4.2.20 on 2025-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/dtmw6jgue/image/upload/v1744804893/media/user_images/Good_things_are_coming_tswgbc.jpg', upload_to='user_images/'),
        ),
    ]
