# Generated by Django 4.2.20 on 2025-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='user_images\\default.png', upload_to='user_images/'),
        ),
    ]
