# Generated by Django 4.2.20 on 2025-04-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='media/user_images/Good_things_are_coming.png', upload_to='user_images/'),
        ),
    ]
