# Generated by Django 4.2.20 on 2025-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='Good_things_are_coming_kb2adg.jpg', upload_to='user_images/'),
        ),
    ]
