# Generated by Django 4.2.20 on 2025-04-17 09:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='Good_things_are_coming_dok1ti', max_length=255, null=True),
        ),
    ]
